name: Set up Node
description: Install Node, pnpm, and dependencies with caching

inputs:
  node-version:
    description: Node.js version to install
    default: '18'
  registry-url:
    description: Registry to configure for publish
  run-install:
    description: Run pnpm install
    default: true

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # v2.2.4

    - name: Install Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: pnpm

    - if: ${{ fromJSON(inputs.run-install) }}
      name: Install dependencies
      shell: bash
      run: pnpm install
