name: Set up Node
description: Install Node, pnpm, and dependencies with caching

inputs:
  setup-node:
    description: Configure Node.js
    default: 'true'
  setup-pnpm:
    description: Configure pnpm
    default: 'true'
  node-version:
    description: Node.js version to install.
    default: '24'
  registry-url:
    description: Registry to configure for publish
  cache:
    description: Cache pnpm store
    default: 'true'
  run-install:
    description: Run pnpm install
    default: 'true'
  standalone:
    description: Install the standalone pnpm binary
    default: 'true'

runs:
  using: composite
  steps:
    - name: Install Node.js ${{ inputs.node-version }}
      if: ${{ inputs.setup-node == 'true' }}
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #v7.0.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}

    - name: Install pnpm
      if: ${{ inputs.setup-pnpm == 'true' }}
      uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      with:
        cache: ${{ inputs.cache }}
        standalone: ${{ inputs.standalone }}
        run_install: ${{ inputs.run-install }}
