name: Set up Node
description: Install Node, pnpm, and dependencies with caching

inputs:
  node-version:
    description: Node.js version to install
    default: '20'
  registry-url:
    description: Registry to configure for publish
  run-install:
    description: Run pnpm install
    default: true

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

    - name: Install Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: pnpm

    - if: ${{ fromJSON(inputs.run-install) }}
      name: Install dependencies
      shell: bash
      run: pnpm install
